### ISSUE TITLE
Remove check for handlers that never match?

### ISSUE THREAD

**Issue by aliak00** [pbackus/sumtype#19]
Hey, I was just thinking of being able to do this:

```
template match(handlers...) {
    auto match(T)(auto ref T value) {
        import sumtype: SumType, match;
        return SumType!T(value).match!handlers;
    }
}
```

So that match can be used as a static type switch statement: e.g.

```
auto r0 = a.match!(
    (string a) => false,
    (int a) => true,
    (float a) => false
);

assert(r0);
```

What do you think?

**Comment by pbackus** [comment]
A generic `match` function for non-`SumType` values isn't a bad idea, but using `SumType` for it seems kind of kludgey. It's probably better to just implement it directly—something like this:

```d
import sumtype: canMatch;

template match(handlers...) {
    auto match(T)(auto ref T val) {
        pure size_t handlerIndex() {
            size_t result = size_t.max;
            static foreach (hid, handler; handlers) {
                static if (canMatch!(handler, T)) {
                    if (result == size_t.max) {
                        result = hid;
                    }
                }
            }

            return result;
        }

        return handlers[handlerIndex](val);
    }
}
```

If you don't want the semantics of `canMatch` (excludes implicit conversions, includes function overloads and objects with `opCall`) you can replace it with `__traits(compiles, handler(val))` and have a version that's totally self-contained.

**Comment by aliak00** [comment]
Ah, yes it was mainly the semantics of your matching that I'm after :D

Thanks!
