### ISSUE TITLE
Regression: Compilation fails with compile-time init of Nullable!T

### ISSUE THREAD

**Issue by aliak00** [pbackus/sumtype#22]
This fails right now:
```
unittest {
	import std.typecons;
	static struct A {
		SumType!(Nullable!int) a = Nullable!int.init;
	}
	A a;
}
```

It was working in 0.8.1. Git bisect revealed the commit that added allowing non-copyable objects (51b3dd8). And the reason it happens is because the constructors call `move`. I'm not sure what the correct solution is though. 

Instead of using `forward` in the constructors, this would fix the compile error:
```
static if (isMutable!T && !isCopyable!T) {
	storage = Storage(move(val));
} else {
	storage = Storage(val);
}
```

But I'm not sure if that's the semantics you want.

**Comment by pbackus** [comment]
The real issue here is that `move` doesn't work in CTFE, but it seems as though that's unlikely to be fixed any time soon [1], so only moving non-copyable types is a reasonable compromise.

[1] https://forum.dlang.org/thread/qdzcfpngunqztrvmcshj@forum.dlang.org
