### ISSUE TITLE
Does not compile with nested self-referential sumtypes

### ISSUE THREAD

**Issue by geezee** [pbackus/sumtype#25]
Using v0.8.6 I get a compilation error when I use nested self-referential SumType types. The smallest program I managed to find that showcases the bug is

```
struct Node(T) { T left; T right; }
alias Tree = SumType!(int, Node!(This*));
alias TrivialTree = SumType!(Tree); // does not compile
alias Forest = SumType!(Tree, Tree[]); // also does not compile
```

The problem happens during the replacement of types. At compile time
`alias TrivialTree = SumType!(Tree)` is treated as `alias TrivialTree = SumType!(SumType!(int, Node!(This*)))`, and `This` is treated as the outer SumType (not the inner one as is expected).

I managed to implement a fix, albeit dirty, that I will improve on in the upcoming days. Here's the gist of it: The SumType template will take an extra template arg and that will be the type to replace. So the previous script becomes

```
struct Node(T) { T left; T right; }
struct TreeRef {}
alias Tree = SumType!(TreeRef, int, Node!(TreeRef*));
alias TrivialTree = SumType!(This, Tree); // will compile since Tree does not use This but rather TreeRef
alias Forest = SumType!(This, Tree, Tree[]); // will also work for the same reason

alias TrivialForest = SumType!(This, Forest); // will not compile
alias AnotherTrivialTree = SumType!(TreeRef, Tree); // will not compile
```

Here's the steps I have in mind for a "better" fix:
1. rename `SumType` struct to `SelfRefSumType`
2. `SelfRefSumType`'s signature becomes`struct SelfRefSumType(ThisRef, TypeArgs...)` (notice the extra `ThisRef` template argument)
3. `alias SumType(TypeArgs...) = SelfRefSumType!(This, TypeArgs)`
4. unittest

I'm not a huge fan of this fix, I think a better one would have the struct create a fresh dummy var for every sumtype and use that. However I'm not entirely sure how to go about doing that.

Attached is a patch that can be applied on top of commit b6a24cb4fbd3cb6c116e49ae8ec78a65ab8055a6 that fixes the bug (but breaks all previous unittests, hence they're removed). Again, I will submit a better PR once I find some time.

[sumtype-0.8.6-patch.txt](https://github.com/pbackus/sumtype/files/3305316/sumtype-0.8.6-patch.txt)

**Comment by geezee** [comment]
The creation of dummy structs (like `This`) can be avoided by changing the `This` struct to a `This` template, like: `struct This(alias T) {}`.
Combined with my previous solution, modify `SumType` to become `struct SumType!(alias s, TypeArgs...)` and replace `This!s` by `typeof(this)` in `TypeArgs`.

This now works:
```d
struct Node(T) { T left; T right; }
alias Tree = SumType!(0, int, Node!(This!0*));
alias TreeForest = SumType!("TF", Tree, Tree[], Node!(Node!(This!"TF"*)));
```
What would be cool is if some reflection can be done to write `alias Tree = SumType!(int, Node!(This!"Tree"*))` and remove the need to pass the first template argument.

**Comment by pbackus** [comment]
I think the correct solution here is simply to avoid descending into the template arguments of any nested `SumType`s when replacing `This` with `typeof(this)`. That way, no occurrence of `This` will ever be replaced more than once.

So, for example:

```d
alias Example = SumType!(This*, SumType!(int, This*));
static assert(is(Example.Types == AliasSeq!(Example*, SumType!(int, This*))));
```

This should be relatively straightforward to implement, and won't require any change to `SumType`'s API.
