### ISSUE TITLE
DIP 1000 issues when creating a `SumType` from a function argument

### ISSUE THREAD

**Issue by SirNickolas** [pbackus/sumtype#29]
```d
nothrow pure @safe @nogc:

alias A = SumType!string;

A createA(string arg) {
    return A(arg);
}

void test() {
    A a = createA("");
}
```

The code above can be successfully compiled (with `-dip1000`) on DMD up to and including 2.085. Starting from 2.086, it produces the following error:

    returning `SumType(cast(ubyte)0u, Storage(null)).this(arg)` escapes a reference to parameter `arg`, perhaps annotate with `return`

But annotating the argument with `return` doesn’t help; neither `return scope` does.

**Comment by SirNickolas** [comment]
Is it possible to test with `__traits(compiles)` if we can add `scope`? Hacky, yes…

**Comment by pbackus** [comment]
This is fixed for `SumType` in `master`, probably by commit fa9f912. The compiler bug remains.
