### ISSUE TITLE
`match` cannot infer `@nogc` with non-template handlers

### ISSUE THREAD

**Issue by SirNickolas** [pbackus/sumtype#31]
Reviving #24.

```d
void main() @safe @nogc {
    import sumtype;

    int acc = 0;
    // `!(string, int)` is OK...
    SumType!(string, int)(1).match!(
        (string _) => 0,
        (int x) => acc += x,
    );
    // But `!(int, string)` is somehow not!
    SumType!(int, string)(1).match!(
        (string _) => 0,
        (int x) => acc += x,
    );
    // src/main.d(1,6): Error: function D main is @nogc yet allocates closures with the GC
    // src/main.d(13,9):        main.main.__lambda4 closes over variable acc at src/main.d(4,9)
}
```

Turns out this issue was fixed only for the last `SumType`’s template parameter.

**Comment by pbackus** [comment]
Reduced version:

```d
template reducedMatch(handlers...)
{
    auto reducedMatch(auto ref SumType!(int, string) self)
    {
        final switch (self.tag) {
            case 0:
                return handlers[0](self.get!int);
            case 1:
                pragma(msg, typeof(handlers[1]));
                return 0;
        }
    }
}

// Github issue #31
@safe @nogc unittest {
    int acc = 0;

    SumType!(int, string)(1).reducedMatch!(
        (int x) => acc += x,
        (string _) => 0,
    );
}
```

This appears to be another manifestation of [dlang issue 19993](https://issues.dlang.org/show_bug.cgi?id=19993), the compiler bug behind issue #24. The exact conditions that trigger the bug are more subtle here: `typeof(handlers[1])` allocates a closure, but `__traits(identifier, handlers[1])` does not. If I had to guess, I'd say the difference is that `typeof` invokes semantic analysis and `__traits(identifier)` doesn't, but that's really just speculation.

I'll see if I can work around this, but it really needs to be fixed in the compiler.

**Comment by pbackus** [comment]
Updated [dlang isssue 19993](https://issues.dlang.org/show_bug.cgi?id=19993) with an example of this error.

**Comment by SirNickolas** [comment]
I guess, if a library does a thing that should be done in the language, it’s inevitably going to reveal bugs in the compiler. Thanks for your efforts!

**Comment by pbackus** [comment]
Can't find a way around the compiler issue, so I'm closing this. For now, unfortunately, you'll have to use a workaround like the one in #24.

**Comment by SirNickolas** [comment]
Wait a minute, I found a way.

```d
template reducedMatch(handlers...)
{
    auto reducedMatch(auto ref SumType!(int, string) self)
    {
        import std.conv: text;

        static foreach (i, h; handlers)
            mixin(`alias handlers`, text(i), ` = h;`);

        final switch (self.tag) {
            case 0:
                return handlers0(self.get!int);
            case 1:
                pragma(msg, typeof(handlers1));
                return 0;
        }
    }
}
```

**Comment by pbackus** [comment]
Amazing; it really works. Well done!
