### ISSUE TITLE
Change type unification rules for `match` regarding `void`?

### ISSUE THREAD

**Issue by SirNickolas** [pbackus/sumtype#32]
I stumble upon the following pattern from time to time:

```d
void processA(A a) { ... }

bool processB(B b, bool someFlag) { ... }

... {
    ...
    x.match!(
        a => processA(a),
        b => processB(b, false), // Error: cannot return non-void from void function.
    );
    ...
}
```

The first handler returns `void`, but the second one returns `bool`, so I have to rewrite it using the longer lambda syntax: `(b) { processB(b, false); }`. And if the first handler returned non-`void`, the error message would be, “mismatched function return type inference of void and bool”—which is more specific, but again, it’s an error.

What do you think about such behaviour as, “if at least one of the handlers returns `void`, then `match` itself returns `void`”? It’s not a breaking change. And if a user did want `match` to return something, but made a mistake and did not return anything from their handler, instead of one of error messages mentioned above they would be told, “expression match(x) is void and has no value”.

**Comment by pbackus** [comment]
This is working as intended. `match` infers its return type the same way every other function in D does, and I have no interest in changing that. I agree that the error message for the `void` case isn't ideal, but that's the compiler's problem, not mine.

If you don't like the "long" lambda syntax, `cast(void) processB(...)` will make the "short" version work.
