### ISSUE TITLE
SumType!(int, bool).match will not compile, depending on argument order

### ISSUE THREAD

**Issue by MetaLang** [pbackus/sumtype#33]
```
alias Boxed = SumType!(int, bool);
Boxed boxed;
boxed.match!(
    (int n) => "int",
    (bool b) => "bool",
    (string s) => s,
);
```

Fails to compile with the message:
```
Error: static assert:  "handler `__lambda3` of type `void delegate(bool b) @safe` never matches"
```

I believe this because of how the matching algorithm is implementation in `matchImpl`:
```
                static foreach (tid, T; Types) {
                    static foreach (hid, handler; handlers) {
                        static if (canMatch!(handler, typeof(self.get!T()))) {
                            if (matches[tid] == noMatch) {
                                matches[tid] = hid;
                            }
                        }
                    }
                }
```

And `canMatch`:
```
enum bool canMatch(alias handler, T) = is(typeof((T arg) => handler(arg)));
```

My assumption is that `canMatch!(handler, typeof(self.get!T()))` matches the handler for `int` to both `bool` _and_ `int` due to the implicit conversion of the former to the latter, and thus incorrectly determines that the _actual_ `bool` handler has no match.

This seems true for any types that can implicitly convert to each-other. Example:
```
    struct S1
    {
    }

    struct S2
    {
        S1 s1;
        alias s1 this;
    }

    alias S = SumType!(S1, S2);
    S().match!(             //Error
        (S1 s1) => "S1",
        (S2 s2) => "S2",
    );
```

In both cases, switching the order of the handlers passed to `match` such that the "subtype" comes first (e.g., `bool` must come before `int` and `S2` must come before `S1`) allows the code to compile.

**Comment by pbackus** [comment]
This is an intentional change, introduced in commit 9d87aa2  and released in `sumtype` version 0.9.0.

There should definitely be an example in the documentation showing how to deal with this, since it's not clear from the error message what the actual problem is.

**Comment by MetaLang** [comment]
This is very bad, because it causes match to incorrectly allow omitting the handler for some types, causing unexpected behaviour:
```
    import sumtype;
    import std.stdio;

    alias Option(T) = SumType!(T, typeof(null));
    bool isNull(T)(SumType!(T, typeof(null)) option) //Should be Option!T, dmd bug
    {
        return option.match!(
            (T t) => false
        );
    }
    Option!string n;
    if (!isNull(n))
        launchTheMissiles(); // RIP
    else
        declarePeace();
```

**Comment by pbackus** [comment]
Your problem is that `typeof(null)` implicitly converts to `string`:

    static assert(is(typeof(null) : string)); // passes

To fix this, use [one of the solutions described in the documentation](https://pbackus.github.io/sumtype/sumtype.match.html#avoiding-unintentional-matches), or use a custom unit type that does not implicitly convert to any other types; e.g.,

    struct Nothing {}
    alias Option(T) = SumType!(Nothing, T);

I understand your frustration. The behavior *is* surprising and unexpected, and if I could fix it *in all possible cases*, I would. Unfortunately, I can't, and I'd rather not pretend I can and have people rely on that, only to run into trouble later when their code gets too complicated for the partial solution to handle.
