### ISSUE TITLE
Member type with copy-constructor fails to compile

### ISSUE THREAD

**Issue by Just-Harry** [pbackus/sumtype#36]
Instantiating a `SumType` with a type that has a defined copy-constructor causes compilation to fail.

This code:

```d
import sumtype;

struct A
{
	int a;

	this (ref typeof(this) source)
	{}
}

alias X = SumType!(A);
```

results in the following error with sumtype v0.9.4:
```
.\sumtype.d(1322): Error: static assert:  "handler #0 of type template never matches"
.\sumtype.d(1165):        instantiated from here: matchImpl!(const(SumType!(A)))
.\sumtype.d(371):        instantiated from here: match!(const(SumType!(A)))
.\test.d(11):        instantiated from here: SumType!(A)
```

Adding another type to the instantiation results in a different error:
```d
struct B
{
	int b;
}

alias Y = SumType!(A, B);
```
```
.\sumtype.d(1344): Error: static assert:  "No matching handler for type B"
.\sumtype.d(1165):        instantiated from here: matchImpl!(SumType!(A, B))
.\sumtype.d(358):        instantiated from here: match!(SumType!(A, B))
.\test.d(16):        instantiated from here: SumType!(A, B)
```

**Comment by pbackus** [comment]
Apologies for the delayed response. Unfortunately, there's a compiler bug ([dlang issue 20842](https://issues.dlang.org/show_bug.cgi?id=20842)) preventing this from getting fixed.

**Comment by pbackus** [comment]
Now blocked by [dlang issue 21198](https://issues.dlang.org/show_bug.cgi?id=21198).

**Comment by pbackus** [comment]
I have this working with current DMD `stable`. Will merge and tag a release as soon as DMD and LDC releases are available with dlang/dmd#11634.

**Comment by Just-Harry** [comment]
Thank you for the fix(es) :)

**Comment by pbackus** [comment]
Unfortunately, attempting to merge the fix for this into `master` reveals that it is once again blocked by a DMD bug: [issue 21348](https://issues.dlang.org/show_bug.cgi?id=21348).

**Comment by pbackus** [comment]
Found a workaround for issue 21348. Hopefully there won't be any more problems...
