### ISSUE TITLE
Error message on no match type

### ISSUE THREAD

**Issue by aliak00** [pbackus/sumtype#38]
I was getting this static assert:

```
Error: static assert:  "handler #1 of type Optional!(Exception) function(return FailureContainer container) pure nothrow @nogc @safe never matches"
```
And for a while I was trying to analyze the first handler, until I switched them around and saw that handler _#0_ was the problem, and then I realized it was zero based :)

So, suggestion to use "first, second, third, etc" in that error message.

Granted that would involve a lot more processing from sumtype. So I understand if you just close this as wontfix or something.

**Comment by aliak00** [comment]
Another suggestion could be to just add a note saying that the numbers are 0-based.

**Comment by pbackus** [comment]
Would writing it as `handlers[0]`, `handlers[1]`, etc. be less confusing?

**Comment by aliak00** [comment]
Yes fer sure!
