### ISSUE TITLE
Add examples of pattern matching to README

### ISSUE THREAD

**Issue by ErichDonGubler** [pbackus/sumtype#6]
This will REALLY get those functional folks going. As it is, though the README example only binds the whole value!

I would have submitted a PR instead, but...I'm not sure what the syntax would be. :)

**Comment by pbackus** [comment]
Currently, `match` only supports binding the whole value.

It would be relatively simple to implement a single level of destructuring, so that you could write code like this:

```d
struct Rectangular { double x, y; }
struct Polar { double r, theta; }
alias Vector = SumType!(Rectangular, Polar);

double length(Vector v)
{
    return v.match!(
        (x, y) => sqrt(x^^2 + y^^2),
        (r, theta) => r
    );
}
```

However, fully-recursive pattern matching like you see in ML-style languages is beyond what D's syntax can support (and without AST macros, there's no way to implement custom syntax short of something like [Pegged](https://code.dlang.org/packages/pegged)).

**Comment by ErichDonGubler** [comment]
This would be good to clarify in the `README.md`, then -- generally when one says "pattern matching" it implies complete destructuring and structuring. Another question I have is about value patterns: Is it possible to use them?

**Comment by pbackus** [comment]
Please refer to [the online documentation](https://pbackus.github.io/sumtype/sumtype.html) for questions about existing functionality.

If you're asking whether it would be possible to *add* support for value patterns, the answer is "probably, but you might not like the result." Syntactically, there are two options:

```d
// Option 1: use default parameter values
slope = vec.match!(
    (double x = 0, double y) => double.nan
    (double x, double y) => y/x,
    // etc.
);

// Option 2: use UDAs on parameters
slope = vec.match!(
    (@value(0) double x, double y) => double.nan,
    (double x, double y) => y/x,
    // etc.
);
```

Option 1 is nicer, but would break existing code that passed functions with default parameter values as arguments to `match`, and potentially cause confusion for anyone who did so by accident in the future. It's also more likely to confuse people reading the code. Option 2 is safer, but much uglier.

I *think* one of the above could be made to work, but the real question is, would it even be worth it? After all, you can already get the same result by just writing an if-else chain:

```d
slope = vec.match!(
    (double x, double y) {
        if (x == 0) return double.nan;
        else return y/x;
    },
    // etc.
);
```

This is slightly less concise than the value-pattern version, but it isn't *that* bad.

**Comment by pbackus** [comment]
It seems like the discussion here has concluded, so I'm closing this. Feel free to open new issues if you'd like to make enhancement requests for destructuring and/or value patterns.
