### ISSUE TITLE
Any plans on making get public?

### ISSUE THREAD

**Issue by iK4tsu** [pbackus/sumtype#64]
Although `SumType` is meant to be a `@safe` algebraic type, sometimes we might want to extract the value from it directly. If the user knows what value is contained within `SumType`, then always resorting to `match`, its heavy usage might become a little tedious to write. I propose making `get`, or other function, public so that this can be avoided. Such function needs to be `@system` as it can lead to undefined behavior.

**Comment by pbackus** [comment]
No, `get` will never be public.

If you want something similar, I suggest a `tryGet` function like the following:

```d
T tryGet(T, ST)(ST st)
    if (isSumType!ST)
{
    return st.tryMatch!((T value) => value);
}
```

This will throw an exception when the requested type is not found.

**Comment by iK4tsu** [comment]
Yes, however that doesn't work with `betterC`. If not `get`, then maybe a `@system` version of it. But if it isn't in your plans, which is understandable, then I'll just keep using `match`.

That being said, I don't think a function to extract the value directly would damage the lib in any way, if it were `@system` and well documented. It would come down to the user's choice if he wanted to use the function or not.

**Comment by pbackus** [comment]
Good API design is as much about what you leave out as about what you include. I want `sumtype` to guide users into [the pit of success][1], and providing a function that crashes at runtime if you use it incorrectly is contrary to that goal.

[1]: https://blog.codinghorror.com/falling-into-the-pit-of-success/

**Comment by iK4tsu** [comment]
How about adding a version of `tryMatch`/`tryGet` suitable for `betterC`. This would `assert` if the requested type wasn't found.

**Comment by pbackus** [comment]
You can write it yourself if you really want it. I will not include such a function in the `sumtype` library, for the reason stated above.

**Comment by FFY00** [comment]
Hold my beer while I fork the standard library for my project... because I want to use something in betterC...?

**Comment by iK4tsu** [comment]
I don't know if this covers all cases, but based on your example above:
```d
T tryGet(T, ST)(ST st)
	if (isSumType!ST)
{
  	static if (st.Types.length == 1)
      	return st.match!((T value) => value);
  	else
      	return st.match!(
        	(T value) => value,
        	function T (_) { assert(false); }
    	);
}
```

Not really what I want, but it might do as a workaround.

**Comment by pbackus** [comment]
Personally I would recommend something like this for BetterC (and in general, honestly):

```d
Nullable!T get(T, ST)(ST st)
    if (isSumType!ST)
{
    return st.match!(
        (value) {
            static if (is(typeof(value) == T))
                return nullable(value);
            else
                return Nullable!T();
        }
    );
}
```
