### ISSUE TITLE
Some assignments should be able to execute in safe code

### ISSUE THREAD

**Issue by iK4tsu** [pbackus/sumtype#67]
```d
void main() @safe
{
	alias SM = SumType!string;
	auto sm = SM("hummm");
	sm = SM("this should be @safe");
}
```

**Comment by pbackus** [comment]
I think the best that can be done here is to allow the assignment if the type being assigned is the only member type that has [unsafe values][1]. This would make the example above `@safe`, but would still require assignments to a `SumType!(string, int[])` to be `@system`.

[1]: https://dlang.org/spec/function.html#safe-values
