### ISSUE TITLE
Support `void` as a type in SumType

### ISSUE THREAD

**Issue by aminya** [pbackus/sumtype#73]
I have been using SumType for error management, but I cannot store `void` in it. This is needed for handling void functions.

**Comment by pbackus** [comment]
This is a limitation of the D language. There is [a draft DIP][1] to lift this limitation, which I hope will eventually be accepted.

Until then, you can work around the limitation in your own code by declaring a custom unit type and using that in place of `void`; for example:

```d
struct Void {}

SumType!(Void, Error) myFunction(/* ... */) { /* ... */ }
```

[1]: https://github.com/dlang/DIPs/pull/173
